const CONFIG = {
  query: 'in:inbox newer_than:7d -label:TRASH -label:SPAM',
  maxThreads: 100,
  dryRun: true,
  aiDryRun: true,
  enableAiForReview: true,
  logSpreadsheetId: '1F2ZNpYVwNqa0-pOuVavJDEf6LahtLNryyoaXYA13EwA',
  digestRecipient: '',
  debugSampleThreads: [],
  debugSenderIncludes: [],
  debugSubjectIncludes: [],
  forceImportantSenders: [
    'accounts.google.com',
    'status.incident.io'
  ],
  forceCommercialSenders: [
    'qwertee.com',
    'steampowered.com',
    'stackcommerce.com',
    'mail.telecompaper.com',
    'substack.com',
    'tldrnewsletter.com',
    'members.netflix.com',
    'bandsintown.com',
    'ticketmaster.',
    'intotheam.com',
    'milkandhoneyprague.club',
    'news.hervis.si',
    'mail.loyaltyteam.com',
    'news.euroleague.net',
    'maap.cc',
    'zdravo.si',
    'ml.spartan.com',
    'booking.com',
    'kompas-shop.si',
    'news@mail.xing.com',
    'karriere.at',
    'uk-umg.com',
    'drclark.si',
    'mailchimpapp.com',
    'kickstarter.com',
    'notifications-noreply@linkedin.com',
    'mailrobot@mail.xing.com',
    'ns.nl',
    'diem25.org',
    'shared1.ccsend.com'
  ],
  forceReviewSenders: [
    'developers.google.com',
    'googledev-noreply@google.com',
    'ifttt.com',
    'ollama.com'
  ],
  forceShippingSenders: [
    'post.at',
    'meinesendung@post.at',
    'amazon.de',
    'notice.aliexpress.com'
  ],
  forceCalendarSenders: [
    'alenka.iskra@gmail.com',
    'sporocanje02@lopolis.si'
  ],
  labels: {
    toRespond: '1: to respond',
    fyi: '2: FYI',
    notification: '3: notification',
    awaitingReply: '6: awaiting reply',
    actioned: '7: actioned',
    review: 'Review/Ambiguous',
    importantServices: 'Important/Services',
    importantFinance: 'Important/Finance',
    importantShipping: 'Important/Shipping',
    importantCalendar: 'Important/Calendar',
    importantOpportunities: 'Important/Opportunities',
    commercialNewsletters: 'Commercial/Newsletters',
    commercialAds: 'Commercial/Ads',
    commercialCampaigns: 'Commercial/Campaigns'
  },
  preserveLabels: [
    'IMPORTANT',
    'STARRED',
    'Osebno',
    '1: to respond',
    '2: FYI',
    '3: notification',
    '5: meeting update',
    '6: awaiting reply',
    '7: actioned',
    'Important/Services',
    'Important/Finance',
    'Important/Shipping',
    'Important/Calendar',
    'Important/Opportunities'
  ],
  preserveSystemLabels: [
    'CATEGORY_PERSONAL'
  ],
  commercialLabels: [
    'Commercial/Newsletters',
    'Commercial/Ads',
    'Commercial/Campaigns'
  ],
  decisionLabels: [
    '1: to respond',
    '2: FYI',
    '3: notification',
    'Review/Ambiguous',
    'Important/Services',
    'Important/Finance',
    'Important/Shipping',
    'Important/Calendar',
    'Important/Opportunities',
    'Commercial/Newsletters',
    'Commercial/Ads',
    'Commercial/Campaigns'
  ],
  responsePatterns: [
    /please respond/i,
    /please reply/i,
    /let me know/i,
    /can you/i,
    /could you/i,
    /would you/i,
    /reply requested/i,
    /rsvp/i,
    /action required/i,
    /confirm/i,
    /your input/i,
    /needs your response/i,
    /waiting for your response/i,
    /review and respond/i,
    /what do you think/i,
    /are you available/i,
    /can we schedule/i
  ],
  fyiPatterns: [
    /for your information/i,
    /fyi/i,
    /sharing this/i,
    /just so you know/i,
    /heads up/i,
    /update for you/i
  ],
  notificationPatterns: [
    /status update/i,
    /system alert/i,
    /incident/i,
    /service notice/i,
    /security alert/i,
    /password reset/i,
    /login alert/i,
    /account alert/i,
    /verification code/i,
    /one-time code/i,
    /otp/i,
    /varnostno opozorilo/i,
    /račun google/i
  ],
  neverArchiveSenders: [
    'incident.io',
    'ezdrav.si',
    'nlb.si',
    'paypal.com',
    'github.com',
    'qmedis.eu'
  ],
  financePatterns: [
    /invoice/i,
    /receipt/i,
    /payment received/i,
    /payment failed/i,
    /statement available/i,
    /order confirmation/i,
    /bank declined/i,
    /billing statement/i
  ],
  shippingPatterns: [
    /tracking number/i,
    /shipment update/i,
    /out for delivery/i,
    /delivered/i,
    /customs/i,
    /parcel/i,
    /package .* delivery/i,
    /in your country\/region/i,
    /delivery update/i,
    /delivery attempted/i,
    /in zustellung/i,
    /sendung/i,
    /paket/i
  ],
  calendarPatterns: [
    /invitation:/i,
    /accepted:/i,
    /declined:/i,
    /tentative:/i,
    /calendar invite/i,
    /meeting update/i,
    /povabilo/i,
    /dogodki/i,
    /prijava na predmete/i
  ],
  opportunityPatterns: [
    /job alert/i,
    /job-e?mpfehl/i,
    /apply to .* role/i,
    /actively recruiting/i,
    /headhunter/i,
    /interview/i,
    /application/i,
    /candidate/i,
    /recruiter/i,
    /recruiting/i,
    /career step/i,
    /position/i,
    /role\b/i,
    /companies are looking for candidates/i
  ],
  opportunityResponsePatterns: [
    /bewerbungsgespräch/i,
    /interview/i,
    /application/i,
    /candidate/i,
    /role/i,
    /position/i
  ],
  opportunityFyiSenders: [
    'jobs@mail.xing.com',
    'jobalerts-noreply@linkedin.com',
    'news@email.experteer.com'
  ],
  newsletterPatterns: [
    /substack/i,
    /newsletter/i,
    /digest/i,
    /roundup/i,
    /briefing/i,
    /tldr/i,
    /reuters/i,
    /telecompaper/i,
    /economist/i,
    /tee-mail/i,
    /project update/i,
    /job-e?mpfehl/i,
    /daily/i,
    /academy/i,
    /build better/i,
    /your posts got .* impressions/i,
    /birthday today/i,
    /resistance beyond borders/i,
    /quiet hiring/i,
    /techcrunch daily/i,
    /latest insights/i,
    /meivakantie/i
  ],
  adPatterns: [
    /sale/i,
    /discount/i,
    /deal/i,
    /offer/i,
    /coupon/i,
    /save now/i,
    /shop now/i,
    /% off/i,
    /free shipping/i,
    /wishlist is now on sale/i,
    /last chance/i,
    /clearance/i,
    /save up to/i,
    /danes poštnine ni/i,
    /popust/i
  ],
  campaignPatterns: [
    /bandsintown/i,
    /ticketmaster/i,
    /members\.netflix\.com/i,
    /festival/i,
    /tour/i,
    /event/i,
    /launch/i,
    /new single/i,
    /screening/i,
    /tickets? available/i,
    /live video/i,
    /races are filling up/i,
    /you'?re missing the start/i,
    /speaker/i,
    /superbloom/i
  ],
  digestThreadLimitPerSection: 8,
  digestLookbackDays: 3,
  digestSearchPool: 120,
  aiModel: 'gemini-2.5-flash',
  aiMaxBodyChars: 2500,
  aiDailyLimit: 15,
  draftModel: 'gemini-3-flash-preview',
  draftFallbackModels: [
    'gemini-3.1-flash-lite-preview',
    'gemini-2.0-flash-lite-001'
  ],
  draftMaxBodyChars: 4000,
  draftDailyLimit: 10,
  draftSearchLookbackDays: 14,
  draftSourceLabels: [
    '1: to respond',
    'Important/Calendar',
    'Important/Services',
    'Important/Opportunities',
    'Review/Ambiguous'
  ],
  draftInstructions: [
    'Write concise, professional, human email replies.',
    'Do not invent facts.',
    'If context is incomplete, keep the reply short and provisional.',
    'Never claim an action was completed unless the thread says so.',
    'Do not mention AI.',
    'If the message is a digest, newsletter, job alert, or broadcast that does not reasonably need a reply, return exactly: NO_DRAFT.',
    'Output plain text only.'
  ].join(' '),
  draftExcludedSenders: [
    'jobalerts-noreply@linkedin.com',
    'jobs@mail.xing.com',
    'jobs-listings@linkedin.com',
    'jobs-noreply@linkedin.com',
    'news@email.experteer.com',
    'm1.email.samsung.com',
    'ifttt.com',
    'ollama.com',
    'maribox.si'
  ],
  draftExcludedSubjectPatterns: [
    /job alert/i,
    /job-e?mpfehl/i,
    /companies are looking for candidates/i,
    /headhunters want to see your profile/i,
    /great companies are looking for candidates/i,
    /free trial/i,
    /voucher/i,
    /premieri/i,
    /new model/i,
    /product update/i
  ],
  draftRetryableStatusCodes: [429, 500, 503]
};
