const CONFIG = {
  query: 'in:inbox newer_than:7d -label:TRASH -label:SPAM',
  maxThreads: 100,
  dryRun: true,
  logSpreadsheetId: '',
  digestRecipient: '',
  debugSampleThreads: [],
  debugSenderIncludes: [],
  debugSubjectIncludes: [],
  forceImportantSenders: [
    'accounts.google.com',
    'status.incident.io'
  ],
  forceCommercialSenders: [
    'qwertee.com',
    'steampowered.com',
    'stackcommerce.com',
    'mail.telecompaper.com',
    'substack.com',
    'tldrnewsletter.com',
    'members.netflix.com',
    'bandsintown.com',
    'ticketmaster.',
    'intotheam.com',
    'milkandhoneyprague.club',
    'news.hervis.si',
    'mail.loyaltyteam.com',
    'news.euroleague.net',
    'maap.cc',
    'zdravo.si',
    'ml.spartan.com'
  ],
  forceReviewSenders: [
    'newsletters-noreply@linkedin.com',
    'developers.google.com'
  ],
  forceShippingSenders: [
    'post.at',
    'meinesendung@post.at',
    'amazon.de',
    'notice.aliexpress.com'
  ],
  labels: {
    toRespond: '1: to respond',
    fyi: '2: FYI',
    notification: '3: notification',
    awaitingReply: '6: awaiting reply',
    actioned: '7: actioned',
    review: 'Review/Ambiguous',
    importantServices: 'Important/Services',
    importantFinance: 'Important/Finance',
    importantShipping: 'Important/Shipping',
    importantCalendar: 'Important/Calendar',
    importantOpportunities: 'Important/Opportunities',
    commercialNewsletters: 'Commercial/Newsletters',
    commercialAds: 'Commercial/Ads',
    commercialCampaigns: 'Commercial/Campaigns'
  },
  preserveLabels: [
    'IMPORTANT',
    'STARRED',
    'Osebno',
    '1: to respond',
    '2: FYI',
    '3: notification',
    '5: meeting update',
    '6: awaiting reply',
    '7: actioned',
    'Important/Services',
    'Important/Finance',
    'Important/Shipping',
    'Important/Calendar',
    'Important/Opportunities'
  ],
  preserveSystemLabels: [
    'CATEGORY_PERSONAL'
  ],
  commercialLabels: [
    'Commercial/Newsletters',
    'Commercial/Ads',
    'Commercial/Campaigns'
  ],
  decisionLabels: [
    '1: to respond',
    '2: FYI',
    '3: notification',
    'Review/Ambiguous',
    'Important/Services',
    'Important/Finance',
    'Important/Shipping',
    'Important/Calendar',
    'Important/Opportunities',
    'Commercial/Newsletters',
    'Commercial/Ads',
    'Commercial/Campaigns'
  ],
  responsePatterns: [
    /please respond/i,
    /please reply/i,
    /let me know/i,
    /can you/i,
    /could you/i,
    /would you/i,
    /reply requested/i,
    /rsvp/i,
    /action required/i,
    /confirm/i,
    /your input/i,
    /needs your response/i,
    /waiting for your response/i,
    /review and respond/i,
    /what do you think/i,
    /are you available/i,
    /can we schedule/i
  ],
  fyiPatterns: [
    /for your information/i,
    /fyi/i,
    /sharing this/i,
    /just so you know/i,
    /heads up/i,
    /update for you/i
  ],
  notificationPatterns: [
    /status update/i,
    /system alert/i,
    /incident/i,
    /service notice/i,
    /security alert/i,
    /password reset/i,
    /login alert/i,
    /account alert/i,
    /verification code/i,
    /one-time code/i,
    /otp/i,
    /varnostno opozorilo/i,
    /račun google/i
  ],
  neverArchiveSenders: [
    'incident.io',
    'ezdrav.si',
    'nlb.si',
    'paypal.com',
    'github.com',
    'google.com',
    'gmail.com',
    'qmedis.eu'
  ],
  financePatterns: [
    /invoice/i,
    /receipt/i,
    /payment received/i,
    /payment failed/i,
    /statement available/i,
    /order confirmation/i,
    /bank declined/i,
    /billing statement/i
  ],
  shippingPatterns: [
    /tracking number/i,
    /shipment update/i,
    /out for delivery/i,
    /delivered/i,
    /customs/i,
    /parcel/i,
    /package .* delivery/i,
    /in your country\/region/i,
    /delivery update/i,
    /delivery attempted/i,
    /in zustellung/i,
    /sendung/i,
    /paket/i
  ],
  calendarPatterns: [
    /invitation:/i,
    /accepted:/i,
    /declined:/i,
    /tentative:/i,
    /calendar invite/i,
    /meeting update/i
  ],
  opportunityPatterns: [
    /job alert/i,
    /headhunter/i,
    /interview/i,
    /application/i,
    /candidate/i,
    /recruiter/i,
    /recruiting/i,
    /career step/i,
    /position/i,
    /companies are looking for candidates/i
  ],
  opportunityResponsePatterns: [
    /bewerbungsgespräch/i,
    /interview/i,
    /application/i,
    /candidate/i,
    /role/i,
    /position/i
  ],
  newsletterPatterns: [
    /substack/i,
    /newsletter/i,
    /digest/i,
    /roundup/i,
    /briefing/i,
    /tldr/i,
    /reuters/i,
    /telecompaper/i,
    /economist/i,
    /tee-mail/i
  ],
  adPatterns: [
    /sale/i,
    /discount/i,
    /deal/i,
    /offer/i,
    /coupon/i,
    /save now/i,
    /shop now/i,
    /% off/i,
    /free shipping/i,
    /wishlist is now on sale/i,
    /last chance/i,
    /clearance/i,
    /popust/i
  ],
  campaignPatterns: [
    /bandsintown/i,
    /ticketmaster/i,
    /members\.netflix\.com/i,
    /festival/i,
    /tour/i,
    /event/i,
    /launch/i,
    /new single/i,
    /screening/i,
    /tickets? available/i,
    /live video/i,
    /races are filling up/i,
    /you'?re missing the start/i
  ]
};
